"""Mock insurance provider dataset. All figures fictional but realistic."""

HEALTH_PROVIDERS = [
    {
        "id": "h_bluepeak",
        "name": "BluePeak Health",
        "logo": "BP",
        "rating": 4.7,
        "reviews": 12840,
        "tagline": "Nationwide network, low deductibles.",
        "base_monthly": 342.0,
        "coverage_reference": 100_000,
        "deductible": 1500,
        "max_out_of_pocket": 6500,
        "network_size": "Nationwide (1.2M providers)",
        "payout_speed": None,
        "features": ["PPO Network", "Telehealth 24/7", "Rx included", "Mental health"],
        "benefits": [
            "$0 preventive care",
            "Virtual visits included",
            "Dental & vision add-on available",
            "Pediatric care 100% covered",
        ],
        "exclusions": ["Cosmetic procedures", "Experimental treatments"],
        "pros": ["Massive network", "Fast claims", "Strong mobile app"],
        "cons": ["Higher premiums", "Specialist referrals required"],
        "badge": "Most Popular",
        "accent_color": "#34C759",
    },
    {
        "id": "h_vitawell",
        "name": "VitaWell Care",
        "logo": "VW",
        "rating": 4.5,
        "reviews": 8210,
        "tagline": "Preventive-first, wellness rewards.",
        "base_monthly": 289.0,
        "coverage_reference": 100_000,
        "deductible": 2000,
        "max_out_of_pocket": 7500,
        "network_size": "Regional+ (620K providers)",
        "features": ["HMO Network", "Wellness rewards", "Fitness reimbursement"],
        "benefits": [
            "$300/yr gym reimbursement",
            "Free annual check-ups",
            "Nutritionist consultations",
            "Chronic care programs",
        ],
        "exclusions": ["Out-of-network care", "Non-emergency out-of-state"],
        "pros": ["Great preventive coverage", "Wellness perks", "Affordable"],
        "cons": ["Smaller network", "HMO restrictions"],
        "badge": "Best Value",
        "accent_color": "#00A86B",
    },
    {
        "id": "h_meridian",
        "name": "Meridian Shield",
        "logo": "MS",
        "rating": 4.6,
        "reviews": 15320,
        "tagline": "Premium coverage for families.",
        "base_monthly": 418.0,
        "coverage_reference": 100_000,
        "deductible": 1000,
        "max_out_of_pocket": 5000,
        "network_size": "Nationwide (980K providers)",
        "features": ["PPO Network", "Maternity", "Pediatric dental", "Rx tier-1 free"],
        "benefits": [
            "Comprehensive maternity coverage",
            "Pediatric dental & vision included",
            "24/7 nurse hotline",
            "Family therapy sessions",
        ],
        "exclusions": ["Weight-loss surgery (unless medically required)"],
        "pros": ["Excellent for families", "Low deductible", "Great customer support"],
        "cons": ["Highest premium", "Complex plan tiers"],
        "badge": "Best for Families",
        "accent_color": "#0071E3",
    },
    {
        "id": "h_northlite",
        "name": "Northlite Basic",
        "logo": "NL",
        "rating": 4.1,
        "reviews": 4720,
        "tagline": "Affordable catastrophic coverage.",
        "base_monthly": 198.0,
        "coverage_reference": 100_000,
        "deductible": 4500,
        "max_out_of_pocket": 9500,
        "network_size": "Regional (280K providers)",
        "features": ["EPO Network", "Catastrophic coverage", "Telehealth"],
        "benefits": [
            "Low monthly premium",
            "Covers major medical events",
            "Free telehealth visits",
        ],
        "exclusions": ["Routine dental", "Vision", "Alternative medicine"],
        "pros": ["Lowest premium", "Simple plan structure"],
        "cons": ["High deductible", "Limited network", "Fewer benefits"],
        "badge": "Cheapest",
        "accent_color": "#86868B",
    },
    {
        "id": "h_evergreen",
        "name": "Evergreen Health Co-op",
        "logo": "EG",
        "rating": 4.8,
        "reviews": 6890,
        "tagline": "Member-owned. Transparent pricing.",
        "base_monthly": 312.0,
        "coverage_reference": 100_000,
        "deductible": 1750,
        "max_out_of_pocket": 6000,
        "network_size": "Nationwide (850K providers)",
        "features": ["PPO Network", "Transparent pricing", "No prior auth for common procedures"],
        "benefits": [
            "Member dividends when profitable",
            "Published prices for procedures",
            "Mental health parity",
            "Integrative medicine covered",
        ],
        "exclusions": ["Elective cosmetic"],
        "pros": ["Highest member satisfaction", "Ethical model", "Balanced benefits"],
        "cons": ["Slightly slower claims", "Fewer specialty add-ons"],
        "badge": "Top Rated",
        "accent_color": "#34C759",
    },
    {
        "id": "h_orion",
        "name": "Orion Digital Health",
        "logo": "OR",
        "rating": 4.4,
        "reviews": 9410,
        "tagline": "App-first health insurance for digital natives.",
        "base_monthly": 264.0,
        "coverage_reference": 100_000,
        "deductible": 2500,
        "max_out_of_pocket": 7000,
        "network_size": "Hybrid (Digital + 450K providers)",
        "features": ["Digital-first", "AI symptom checker", "Instant claim reimbursement"],
        "benefits": [
            "Instant claims via app",
            "AI-powered health assistant",
            "Same-day telehealth",
            "Wearable device integration",
        ],
        "exclusions": ["Home visits", "Concierge medicine"],
        "pros": ["Best-in-class app", "Fast reimbursements", "Modern experience"],
        "cons": ["Less phone support", "Smaller in-person network"],
        "badge": "Best App",
        "accent_color": "#5E5CE6",
    },
]

LIFE_PROVIDERS = [
    {
        "id": "l_atlas",
        "name": "Atlas Guardian Life",
        "logo": "AG",
        "rating": 4.8,
        "reviews": 18420,
        "tagline": "Trusted for over 100 years.",
        "base_monthly": 38.0,
        "coverage_reference": 500_000,
        "deductible": 0,
        "max_out_of_pocket": None,
        "payout_speed": "5–7 business days",
        "network_size": None,
        "features": ["Term life", "Convertible to whole life", "No medical exam up to $1M"],
        "benefits": [
            "Level premium guaranteed",
            "Terminal illness rider included",
            "Waiver of premium on disability",
        ],
        "exclusions": ["Death from illegal activity (first 2 years)", "Suicide clause (2 years)"],
        "pros": ["Excellent financial rating (A++)", "Fast underwriting", "No exam option"],
        "cons": ["Slightly higher premiums", "Limited whole-life options"],
        "badge": "Top Rated",
        "accent_color": "#34C759",
    },
    {
        "id": "l_haven",
        "name": "Haven Term",
        "logo": "HV",
        "rating": 4.6,
        "reviews": 9820,
        "tagline": "Simple, digital term life.",
        "base_monthly": 28.0,
        "coverage_reference": 500_000,
        "deductible": 0,
        "payout_speed": "3–5 business days",
        "features": ["Term life only", "100% online application", "Instant decision"],
        "benefits": [
            "Apply in under 10 minutes",
            "Coverage up to $3M",
            "No medical exam for many applicants",
        ],
        "exclusions": ["No permanent life options", "Suicide clause (2 years)"],
        "pros": ["Lowest premiums", "Fastest online experience", "Easy renewal"],
        "cons": ["Term only (no whole life)", "Limited riders"],
        "badge": "Best Value",
        "accent_color": "#00A86B",
    },
    {
        "id": "l_meridian",
        "name": "Meridian Legacy",
        "logo": "ML",
        "rating": 4.7,
        "reviews": 14210,
        "tagline": "Whole life & wealth transfer.",
        "base_monthly": 52.0,
        "coverage_reference": 500_000,
        "deductible": 0,
        "payout_speed": "7–10 business days",
        "features": ["Whole life", "Cash value accumulation", "Dividend-paying"],
        "benefits": [
            "Lifetime coverage",
            "Cash value grows tax-deferred",
            "Loan against policy",
            "Annual dividends (mutual company)",
        ],
        "exclusions": ["Suicide clause (2 years)"],
        "pros": ["Lifetime protection", "Builds cash value", "Estate planning ready"],
        "cons": ["Higher premiums", "Slower approval"],
        "badge": "Best Whole Life",
        "accent_color": "#0071E3",
    },
    {
        "id": "l_pinepoint",
        "name": "PinePoint Term",
        "logo": "PP",
        "rating": 4.3,
        "reviews": 5610,
        "tagline": "No-frills, low-cost term life.",
        "base_monthly": 22.0,
        "coverage_reference": 500_000,
        "deductible": 0,
        "payout_speed": "10–14 business days",
        "features": ["Term life", "Medical exam required", "Low premiums"],
        "benefits": ["Very low rates for healthy applicants", "Level premiums"],
        "exclusions": ["High-risk activities", "Suicide clause (2 years)"],
        "pros": ["Cheapest available", "Straightforward terms"],
        "cons": ["Medical exam required", "Slower underwriting", "Basic policy"],
        "badge": "Cheapest",
        "accent_color": "#86868B",
    },
    {
        "id": "l_northstar",
        "name": "NorthStar Family",
        "logo": "NS",
        "rating": 4.5,
        "reviews": 7420,
        "tagline": "Built for families with kids.",
        "base_monthly": 34.0,
        "coverage_reference": 500_000,
        "deductible": 0,
        "payout_speed": "5–7 business days",
        "features": ["Term life", "Child rider", "Spouse rider available"],
        "benefits": [
            "Add children for $5/mo each",
            "Spouse coverage add-on",
            "College tuition rider option",
        ],
        "exclusions": ["Suicide clause (2 years)"],
        "pros": ["Great family bundles", "Flexible riders", "Simple pricing"],
        "cons": ["Limited coverage caps", "Fewer investment options"],
        "badge": "Best for Families",
        "accent_color": "#FF9500",
    },
    {
        "id": "l_apex",
        "name": "Apex Universal",
        "logo": "AX",
        "rating": 4.4,
        "reviews": 6180,
        "tagline": "Flexible universal life.",
        "base_monthly": 46.0,
        "coverage_reference": 500_000,
        "deductible": 0,
        "payout_speed": "7–10 business days",
        "features": ["Universal life", "Adjustable premiums", "Investment component"],
        "benefits": [
            "Adjust coverage & premium over time",
            "Cash value linked to interest rates",
            "Flexible death benefit",
        ],
        "exclusions": ["Suicide clause (2 years)"],
        "pros": ["Ultimate flexibility", "Cash value growth", "Adjustable"],
        "cons": ["Complex to understand", "Requires monitoring"],
        "badge": "Most Flexible",
        "accent_color": "#5E5CE6",
    },
]
