#!/usr/bin/env node
/**
 * Emits the stable entry point the Webflow snippet points at.
 *
 * Why this exists
 * ---------------
 * Two requirements pull in opposite directions. The Webflow snippet must never
 * change, which wants a fixed filename. Caching must be correct, which wants a
 * content hash in the filename. GitHub Pages serves everything with
 * max-age=600 and that header cannot be configured, so a fixed filename means
 * a visitor can hold a stale copy for ten minutes after every deploy, and can
 * end up running old CSS against new JS.
 *
 * The loader resolves both. The bundles are content-hashed, so a changed file
 * is a changed URL and is never served stale. This file keeps the fixed name
 * and simply names the current pair, so the two always arrive together.
 *
 * It is deliberately written to the SAME path the old snippet already used
 * (static/js/gmc-tool.js). An existing embed therefore keeps working without
 * being edited: its script tag now loads this loader, and its stylesheet link
 * 404s harmlessly because the loader injects the real stylesheet itself.
 *
 * Run automatically after `npm run build`.
 */
const fs = require("fs");
const path = require("path");

const BUILD = path.resolve(__dirname, "..", "build");
const MANIFEST = path.join(BUILD, "asset-manifest.json");
const OUT = path.join(BUILD, "static", "js", "gmc-tool.js");

function fail(message) {
  console.error("\n[build-loader] " + message + "\n");
  process.exit(1);
}

if (!fs.existsSync(MANIFEST)) {
  fail("No asset-manifest.json in build/. Run the build first.");
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
const entries = manifest.entrypoints || [];

const jsEntry = entries.find((f) => f.endsWith(".js"));
const cssEntry = entries.find((f) => f.endsWith(".css"));

if (!jsEntry) fail("No JS entrypoint in asset-manifest.json.");
if (!cssEntry) fail("No CSS entrypoint in asset-manifest.json.");

// Entrypoints are recorded relative to the build root, e.g.
// "static/js/gmc-tool.1a2b3c4d.js". Keep only the filename; the loader
// resolves directories relative to its own URL.
const jsFile = path.posix.basename(jsEntry);
const cssFile = path.posix.basename(cssEntry);

if (jsFile === "gmc-tool.js") {
  fail(
    "The JS entrypoint is unhashed, so this loader would overwrite the real " +
      "bundle. Check the contenthash filenames in craco.config.js.",
  );
}

const loader = `/* Generated by scripts/build-loader.js. Do not edit.
   Fixed URL for the Webflow snippet. Injects the content-hashed pair below,
   so CSS and JS are always from the same build and neither is ever cached
   stale. Regenerated on every deploy. */
(function () {
  var CSS = ${JSON.stringify(cssFile)};
  var JS = ${JSON.stringify(jsFile)};

  var self =
    document.currentScript ||
    document.querySelector('script[src*="static/js/gmc-tool.js"]');
  if (!self || !self.src) return;

  // Strip "static/js/<file>" to get the deploy root, so the tool can be
  // served from any sub-path without being rebuilt.
  var base = self.src.replace(/static\\/js\\/[^/?#]*(\\?.*)?(#.*)?$/, "");

  var head = document.head || document.getElementsByTagName("head")[0];

  if (!document.querySelector('link[data-gmc-tool]')) {
    var link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = base + "static/css/" + CSS;
    link.setAttribute("data-gmc-tool", "");
    head.appendChild(link);
  }

  if (!document.querySelector('script[data-gmc-tool]')) {
    var script = document.createElement("script");
    script.src = base + "static/js/" + JS;
    script.defer = true;
    script.setAttribute("data-gmc-tool", "");
    (document.body || head).appendChild(script);
  }
})();
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, loader, "utf8");

console.log("[build-loader] static/js/gmc-tool.js -> " + cssFile + " + " + jsFile);
